RiotSharp/MatchEndpoint/Participant.cs

Added highest achieved season tier attribute to match summary

---

RiotSharp/LeagueEndpoint/Converters/Tier.cs
RiotSharp/LeagueEndpoint/Converters/TierConverter.cs

Add Unranked tier to Tier enum

---

RiotSharp/RiotApi.cs
RiotSharpTest/RiotApiTest.cs

Adds Master Tier to the API, using the same general code in GetChallenger functions.

Add Master Tier

---

RiotSharpExample/App.config
RiotSharpExample/Program.cs
RiotSharpTest/App.config
RiotSharpTest/RiotApiTest.cs
RiotSharpTest/SummonerTest.cs

As long as you provide a valid API key now, the tests should pass.  It took a while to find summoner IDs and team IDs that would cause the tests to pass.  This is really just a convenience for other contributors.

Update tests so they can pass with valid key

---

RiotSharp/CurrentGameEndpoint/BannedChampion.cs
RiotSharp/CurrentGameEndpoint/CurrentGame.cs
RiotSharp/CurrentGameEndpoint/Mastery.cs
RiotSharp/CurrentGameEndpoint/Observer.cs
RiotSharp/CurrentGameEndpoint/Participant.cs
RiotSharp/CurrentGameEndpoint/Rune.cs
RiotSharp/FeaturedGamesEndpoint/FeaturedGames.cs
RiotSharp/Misc/MapType.cs
RiotSharp/Misc/Platform.cs
RiotSharp/Misc/PlatformConverter.cs

I found some other tabbed source files in RiotSharp and formatted them with the project's 4 space indentation policy, excluding the 2 files already fixed in #141 .

Changed Tabs -> Space Indentation in Source Files

---

RiotSharp/CurrentGameEndpoint/Converters/GameQueueType.cs
RiotSharp/CurrentGameEndpoint/Converters/GameQueueTypeConverter.cs
RiotSharp/GameEndpoint/Converters/GameSubType.cs
RiotSharp/GameEndpoint/Converters/GameSubTypeConverter.cs
RiotSharp/MatchEndpoint/Converters/QueueType.cs
RiotSharp/MatchEndpoint/Converters/QueueTypeConverter.cs

Added Butcher's Bridge (ARAM skin) and Black Market Brawlers (featured game mode) to the CurrentGame, Game, and Match endpoints.

Bilgewater Game Modes

---

RiotSharp/StaticDataEndpoint/Champion/ParTypeStatic.cs
RiotSharp/StaticDataEndpoint/Champion/ParTypeStaticConverter.cs

Add ParType MP

---

appveyor.yml

[RS-158] appveyor.yml

---

RiotSharp/ChampionEndpoint/ChampionList.cs
RiotSharp/CurrentGameEndpoint/Participant.cs
RiotSharp/FeaturedGamesEndpoint/FeaturedGames.cs
RiotSharp/GameEndpoint/RecentGames.cs
RiotSharp/IRiotApi.cs
RiotSharp/IStaticRiotApi.cs
RiotSharp/IStatusRiotApi.cs
RiotSharp/MatchEndpoint/MatchReference.cs
RiotSharp/Misc/TimeSpanConverterFromMS.cs
RiotSharp/Misc/TimeSpanConverterFromS.cs
RiotSharp/StaticDataEndpoint/MapStaticWrapper.cs
RiotSharp/StatsEndpoint/PlayerStatsSummaryList.cs
RiotSharp/StatsEndpoint/RankedStats.cs
RiotSharp/StatusEndpoint/Message.cs
RiotSharp/StatusEndpoint/ShardStatus.cs
RiotSharp/SummonerEndpoint/MasteryPages.cs
RiotSharp/SummonerEndpoint/RunePages.cs
RiotSharp/SummonerEndpoint/SummonerBaseList.cs
RiotSharpTest/RiotApiExceptionTest.cs
RiotSharpTest/RiotApiTest.cs
RiotSharpTest/StaticRiotApiTest.cs
RiotSharpTest/StatusRiotApiTest.cs
RiotSharpTest/SummonerTest.cs

[RS-168] Fix unused imports and import ordering

---

README.md

[RS-159] Add a few badges

---

RiotSharp/RiotSharp.csproj
RiotSharp/packages.config
RiotSharpExample/RiotSharpExample.csproj
RiotSharpExample/packages.config

[RS-166] Udpdate json.NET to 8.0.1

---

.gitignore
RiotSharpExample/App.config
RiotSharpTest/App.config
appveyor.yml

[RS-173] Add the tournament api key

---

README.md

[RS-154] Document the other apis in the readme

---

RiotSharp/Properties/AssemblyInfo.cs
appveyor.yml

[RS-179] Release 2.4

---

RiotSharp/Properties/AssemblyInfo.cs

Modified Assembly CR Year - Fixes #182

Modified Assembly CR Year - Fixes #182

---

RiotSharp/MatchEndpoint/Converters/QueueType.cs
RiotSharp/MatchEndpoint/Converters/QueueTypeConverter.cs
RiotSharp/MatchEndpoint/Converters/WardType.cs
RiotSharp/MatchEndpoint/Converters/WardTypeConverter.cs

Together with the previous PR this should incorporate all changes in https://developer.riotgames.com/discussion/community-discussion/show/N9Uh1sWt

Added blue trinket to WardType enum and new team builder queue type to QueueType enum.

---

RiotSharp/Misc/Queue.cs
RiotSharp/Misc/QueueConverter.cs

Updated the files used in public RiotApi.GetMatchList()

Added new team builder to Queue enum

---

RiotSharp/Misc/Slug.cs
RiotSharp/Requester.cs
RiotSharp/RiotSharp.csproj
RiotSharp/StatusEndpoint/Shard.cs
RiotSharpExample/App.config
RiotSharpTest/App.config
RiotSharpTest/RiotApiTest.cs
RiotSharpTest/StatusRiotApiTest.cs

[RS-189] Unit tests are failing

---

RiotSharp/CurrentGameEndpoint/Converters/GameQueueType.cs
RiotSharp/CurrentGameEndpoint/Converters/GameQueueTypeConverter.cs

Hope this fixes the issue I brought up earlier.
Again sorry not sure about the etiquette involved with pull requests/issues so sorry if there is a duplicates.

Added New QueueTypes to Converters in CurrentGameEndpoint

---

RiotSharp/Requester.cs
RiotSharpTest/App.config
RiotSharpTest/RiotApiExceptionTest.cs
RiotSharpTest/RiotApiTest.cs
RiotSharpTest/StaticRiotApiExceptionTest.cs
appveyor.yml

[RS-201] Package restore doesnt work with Microsoft.Bcl.Build in AppVeyor

---

appveyor.yml

Integrate gitter and appveyor

---

RiotSharp/RiotApi.cs
RiotSharp/RiotSharp.csproj

Suppress warning 1591 to remove warning clutter described in #162. Also fix a couple of related warnings.

Reduce the number of warnings

---

RiotSharp/IRiotApi.cs
RiotSharp/IStaticRiotApi.cs
RiotSharp/IStatusRiotApi.cs
RiotSharp/ITournamentRiotApi.cs
RiotSharp/RiotSharp.csproj

Only suppress warning 1591 in certain files and not in the whole project. Files in which to suppress are discussed in #162

Suppress warning 1591 in certain files

---

RiotSharp/ChampionMasteryEndpoint/ChampionMastery.cs
RiotSharp/IRiotApi.cs
RiotSharp/RiotApi.cs
RiotSharp/RiotSharp.csproj
RiotSharpTest/RiotApiTest.cs

As said in #195 new API has been added and it was missing from wrapper. Add support for new API and tests for it.

Add wrapper for champion mastery api.

---

RiotSharp/StatusEndpoint/Message.cs

Tests regarding shard status are failing

---

RiotSharpTest/RiotApiTest.cs

Get champions free to play unit tests are failing

---

RiotSharp/CurrentGameEndpoint/Participant.cs

Removed SummonId from Participant in the current/featured game endpoint

---

README.md

Mention up-for-grabs in the readme

---

RiotSharp/StaticDataEndpoint/DataRequested.cs

Add documentation for `none` on DataRequested enum

---

RiotSharp/Misc/Queue.cs
RiotSharp/Misc/QueueConverter.cs

when i use "JsonConvert.DeserializeObject<RiotSharp.MatchEndpoint.MatchList>(jsoni)", i got null reference error. i hope now working good.

Fix Queue's toCustomString 

---

RiotSharp/IStaticRiotApi.cs
RiotSharp/StaticRiotApi.cs

Hi,
Were these changes required?

Replace default version in the static endpoints

---

RiotSharp/StatusEndpoint/Incident.cs

Looks like they changed the ID to string.

Change ID type from long to string

---

RiotSharp/Misc/GameMode.cs
RiotSharp/Misc/GameModeConverter.cs

Added the new game mode. Tests that were failing because of this are now passing.

Added new Siege mode to fix issue #246.

---

RiotSharp/packages.config
RiotSharpTest/RiotApiTest.cs
RiotSharpTest/TournamentRiotApiTest.cs
appveyor.yml

Added code coverage

---

RiotSharp/MatchEndpoint/Enums/Converters/QueueTypeConverter.cs
RiotSharp/MatchEndpoint/Enums/Converters/SeasonConverter.cs
RiotSharp/MatchEndpoint/Enums/QueueType.cs
RiotSharp/MatchEndpoint/Enums/Season.cs
RiotSharp/Misc/Queue.cs
RiotSharp/Misc/QueueConverter.cs
RiotSharp/Properties/AssemblyInfo.cs
RiotSharp/StatsEndpoint/Enums/Converters/PlayerStatsSummaryTypeConverter.cs
RiotSharp/StatsEndpoint/Enums/PlayerStatsSummaryType.cs

Add missing enum values related to the 2017 season and the new ranked flex games

---

RiotSharp/CurrentGameEndpoint/Enums/Converters/GameQueueTypeConverter.cs
RiotSharp/CurrentGameEndpoint/Enums/GameQueueType.cs

Updated GameQueueType for the current game endpoint

---

RiotSharp/IRiotApi.cs
RiotSharp/RiotApi.cs
RiotSharpTest/RiotApiTest.cs

Renamed GetAll and GetTop champion mastery methods.

SegFault255 branch

---

RiotSharp/Misc/Region.cs
RiotSharp/Misc/RegionConverter.cs

Added jp region

---

RiotSharpTest/TournamentRiotApiTest.cs

Reenabled tournament API tests

---

RiotSharp/Requester.cs
RiotSharp/RiotSharpException.cs
RiotSharpTest/RiotApiTest.cs

Closed the old pull request (#293) since it was on the wrong branch
#292 (not a full fix)

RiotSharpException store source HttpStatusCode (new)

---

RiotSharp/RiotApi.cs

I accidentally committed to the wrong branch again...

Make grouped async calls asynchronous (new branch)

---

RiotSharp/CurrentGameEndpoint/Participant.cs

fix SummonuerSpell1 typo

---

RiotSharp/MatchEndpoint/Enums/Converters/MonsterSubTypeConverter.cs
RiotSharp/MatchEndpoint/Enums/MonsterSubType.cs
RiotSharp/MatchEndpoint/Event.cs
RiotSharp/RiotSharp.csproj

#309 
Haven't tested yet, will comment when I test.

adding MonsterSubType enum & field

---

RiotSharp/MatchEndpoint/MatchReference.cs

Add missing Region property for #303

[RS-303] Add Region property to MatchReference

---

RiotSharp/StaticDataEndpoint/Champion/Enums/Converters/ParTypeStaticConverter.cs
RiotSharp/StaticDataEndpoint/Champion/Enums/ParTypeStatic.cs

Fixes StaticRiotApi.GetChampions

Add missing par types

---

RiotSharp/StatsEndpoint/Enums/Converters/PlayerStatsSummaryTypeConverter.cs
RiotSharp/StatsEndpoint/Enums/PlayerStatsSummaryType.cs

To solve Kiritsu's issue raised in Gitter chat.

add Assassinate Player Stats Summary Type

---

RiotSharp/MatchEndpoint/Enums/Converters/MonsterTypeConverter.cs

Reverts BenFradet/RiotSharp#338

Revert "Update MonsterTypeConverter.cs"

---

RiotSharp/MatchEndpoint/Enums/Converters/MonsterTypeConverter.cs

Added support for the Rift Herald into the Monster Type Converter

Added RiftHerald

---

RiotSharp/Misc/CultureInfoExtensions.cs
RiotSharp/RiotSharp.csproj
RiotSharpTest/Misc/CultureInfoExtensionsTest.cs
RiotSharpTest/RiotSharpTest.csproj

Added `CultureInfo` extension method `ToLanguage `and corresponding unit tests

Added CultureInfo extension method ToLanguage (#357)

---

RiotSharp/IRiotApi.cs
RiotSharp/IStaticRiotApi.cs
RiotSharp/IStatusRiotApi.cs
RiotSharp/ITournamentRiotApi.cs
RiotSharp/RiotApi.cs
RiotSharp/StaticRiotApi.cs
RiotSharp/StatusRiotApi.cs
RiotSharp/TournamentRiotApi.cs

Moved documentation from Api classes to Api interfaces.

Moved documentation from Api classes to Api interfaces (#358)

---

RiotSharpTest/RiotApiTest.cs
RiotSharpTest/TournamentRiotApiTest.cs

Replaced the integer with a long as mentioned in issue #373.

Intoverflow#373

---

RiotSharp/Requester.cs

Added 429 Error. Fixes 1/2 of issue #378

---

RiotSharp/IRiotApi.cs
RiotSharp/RiotApi.cs
RiotSharp/SummonerEndpoint/SummonerBase.cs
RiotSharpExample/Program.cs
RiotSharpTest/RiotApiTest.cs
RiotSharpTest/SummonerTest.cs
RiotSharpTest/TournamentRiotApiTest.cs

Removes all references to teams in the test files, constant files, and wrapper files.

Remove team - Issue#370

---

RiotSharp/Http/Interfaces/IRateLimitedRequester.cs
RiotSharp/Http/RateLimitedRequester.cs
RiotSharp/Http/RequesterBase.cs
RiotSharp/Interfaces/IRiotApi.cs
RiotSharp/RiotApi.cs
RiotSharp/StaticRiotApi.cs
RiotSharp/StatusRiotApi.cs
RiotSharp/SummonerEndpoint/SummonerBase.cs
RiotSharp/TournamentRiotApi.cs
RiotSharpExample/Program.cs
RiotSharpTest/App.config
RiotSharpTest/CommonTestBase.cs
RiotSharpTest/RiotApiExceptionTest.cs
RiotSharpTest/RiotApiTest.cs
RiotSharpTest/SummonerTest.cs

Moved summoner endpoint to V3 and removed depricated methods.
Added `usePlatforms` option to `CreateGetRequest` method  in `RateLimitedRequester` to add compatibility for the new platform endpoints.
Adjusted unit tests.

Migrated summoner endpoint to V3

---

RiotSharp/CurrentGameEndpoint/Enums/GameQueueType.cs
RiotSharp/MatchListEndPoint/Queue.cs
RiotSharp/Misc/GameMode.cs
RiotSharp/Misc/MapType.cs

Added new darkstar game mode #390

Added Darkstar game mode

---

README.md

The Links were no longer supported....

Changed links to Documentations!

---

RiotSharp/Http/Interfaces/IRequester.cs
RiotSharp/Http/RateLimitedRequester.cs
RiotSharp/Http/Requester.cs
RiotSharp/Http/RequesterBase.cs
RiotSharp/Interfaces/IStaticRiotApi.cs
RiotSharp/RiotSharp.csproj
RiotSharp/StaticDataEndpoint/ProfileIcons/Cache/ProfileIconsStaticWrapper.cs
RiotSharp/StaticDataEndpoint/ProfileIcons/ProfileIconListStatic.cs
RiotSharp/StaticDataEndpoint/ProfileIcons/ProfileIconStatic.cs
RiotSharp/StaticDataEndpoint/SummonerSpell/SummonerSpell.cs
RiotSharp/StaticRiotApi.cs
RiotSharpTest/StaticRiotApiTest.cs

Moved static data endpoint to V3 and improved RequesterBase

---

RiotSharp/RiotApi.cs
RiotSharpTest/App.config
RiotSharpTest/RiotApiTest.cs
RiotSharpTest/RiotApiTestBase.cs

Fixed GetMatch includeTimeline parameter parsing issue

---

RiotSharp.AspNetCore/ApiKey.cs
RiotSharp.AspNetCore/IServiceCollectionExtension.cs
RiotSharp.AspNetCore/RiotSharp.AspNetCore.csproj
RiotSharp.AspNetCore/RiotSharpOptions.cs
RiotSharp.sln
appveyor.yml

This is the first version of the default DI implementation for ASP.NET Core.
**Current known issues:**
Using project reference instead of NuGet package
Missing unit tests

ASP.NET Core DI (WIP)

---

RiotSharp/Interfaces/IRiotApi.cs
RiotSharp/RiotApi.cs
RiotSharpTest/CommonTestBase.cs
RiotSharpTest/RiotApiTest.cs

Just moving the masteries to V3.

move masteries to v3

---

RiotSharp/GameEndpoint/Enums/Converters/GameSubTypeConverter.cs
RiotSharp/GameEndpoint/Enums/GameSubType.cs

Fixes #424 
I suggest we publish this as a maintenance patch.

Added missing Darkstar GameSubType

---

RiotSharp.Test/RiotApiTest.cs
RiotSharp/RiotApi.cs

Hey,
Migrated the champions api to v3
Had to change the tests also - tests checked for 10 f2p champions which is no longer correct.
BTW, That's my first PR.

champions v3

---

RiotSharp.AspNetCore/IServiceCollectionExtension.cs
RiotSharp.AspNetCore/MemoryCache.cs
RiotSharp.AspNetCore/RiotSharp.AspNetCore.csproj
RiotSharp.AspNetCore/RiotSharpOptions.cs
RiotSharp.Test/MemoryCacheTest.cs
RiotSharp.Test/RiotSharp.Test.csproj
RiotSharp/Cache.cs
RiotSharp/ICache.cs

Resolves #435 
Removed some unnecessary methods from `ICache`.

Implemented ICache with IMemoryCache for AspNetCore

---

RiotSharp.Test/RiotApiTest.cs
RiotSharp.Test/StaticRiotApiTest.cs
RiotSharp.Test/StatusRiotApiTest.cs

First off, apologies if I'm not doing this right. Attempting my first pull request :)
Targets the 3 points raised in #270.
I can't verify the 8 tournament tests as I'm still waiting for a tournament API key. However I didn't need to touch these tests so I'm reasonably confident that no harm has been done. All other tests passing as before.

#270 use better assertions

---

RiotSharp.Example/Program.cs
RiotSharp.Test/RiotApiTest.cs
RiotSharp.Test/StatusRiotApiTest.cs
RiotSharp/Http/Interfaces/IRateLimitedRequester.cs
RiotSharp/Http/Interfaces/IRequester.cs
RiotSharp/Http/RateLimitedRequester.cs
RiotSharp/Http/Requester.cs
RiotSharp/Interfaces/IRiotApi.cs
RiotSharp/Interfaces/IStatusRiotApi.cs
RiotSharp/RiotApi.cs
RiotSharp/StatusRiotApi.cs

Fixes #348 
TODO:
~~Remove `usePlatform` parameter from `RateLimitedRequester`~~

Migrated champion mastery endpoint to v3

---

RiotSharp.AspNetCore/ApiKeyOptions.cs
RiotSharp.AspNetCore/IServiceCollectionExtension.cs
RiotSharp.AspNetCore/MemoryCache.cs
RiotSharp.AspNetCore/RiotSharpOptions.cs
RiotSharp.Example/Program.cs
RiotSharp.Test/StaticRiotApiExceptionTest.cs
RiotSharp.Test/StaticRiotApiTest.cs
RiotSharp/Http/Requesters.cs
RiotSharp/Interfaces/IStaticRiotApi.cs
RiotSharp/PassThroughCache.cs
RiotSharp/StaticDataEndpoint/DataRequested.cs
RiotSharp/StaticRiotApi.cs

- Add basic rate limiting
- Add option to disable caching
- Add option for setting caching time
- Changed default data of static methods from basic to all, fixes #432
- Change enum naming to start with a capital letter, fixes #386

Add basic rate limiting to StaticRiotApi and option to disable cache

---

RiotSharp/StaticDataEndpoint/StatsStatic.cs

Added documentation per Issue #217, not sure if this is the correct branch to open a pull request for, apologies if I missed anything.

Added documentation to StatsStatic.

---

RiotSharp/StaticRiotApi.cs

Found a null check that could be improved. Feel free to decline if you don't like this syntax.

Null check improvement

---

RiotSharp.Test/RateLimiterTest.cs
RiotSharp/Http/RequesterBase.cs
RiotSharp/RiotApi.cs
RiotSharp/StaticRiotApi.cs
RiotSharp/TournamentRiotApi.cs

Reverted back string interpolation + fix .toString() => .ToString() 
Related to the closed #469 issue

Fix string interpolation

---

RiotSharp/RiotApi.cs

Here is the PR @BenFradet 
This should be completely okay with this...

Removing forgotten lines making the compilation crash.

---

RiotSharp/FileCache.cs
RiotSharp/SummonerEndpoint/Summoner.cs
RiotSharp/SummonerEndpoint/SummonerBase.cs

Removed override keywords from FileCache implementation, which broke the build.
Remove service methods from SummonerBase

Removed service methods from SummonerBase and fixed build

---

RiotSharp.AspNetCore/ApiKeyOptions.cs
RiotSharp.AspNetCore/DistributedCache.cs
RiotSharp.AspNetCore/HybridCache.cs
RiotSharp.AspNetCore/IDistributedCacheExtensions.cs
RiotSharp.AspNetCore/IServiceCollectionExtension.cs

WIP
@BenFradet  What are you thoughts about this?

Add a distributed cache implementation for ASP.NET Core

---

RiotSharp/Http/RequesterBase.cs
RiotSharp/Misc/Region.cs
RiotSharp/TournamentRiotApi.cs

Add regional proxy regions and change tournament host from global to Americas

---

RiotSharp.Test/EndpointTests/ThirdPartyEndpointTests.cs
RiotSharp.Test/RiotApiTest.cs
RiotSharp.Test/RiotApiTestBase.cs
RiotSharp/Endpoints/Interfaces/IThirdPartEndpoint.cs
RiotSharp/Endpoints/ThirdPartEndpoint/ThirdPartyEndpoint.cs
RiotSharp/Interfaces/IRiotApi.cs
RiotSharp/RiotApi.cs

ThirdParty Endpoint implementation.

Add third-party-code-v3 Endpoint #500

---

RiotSharp.AspNetCore/DistributedCache.cs
RiotSharp.AspNetCore/HybridCache.cs
RiotSharp.AspNetCore/IServiceCollectionExtension.cs
RiotSharp.AspNetCore/MemoryCache.cs
RiotSharp.Test/CacheTest.cs
RiotSharp.Test/MemoryCacheTest.cs
RiotSharp.Test/StaticRiotApiTest.cs
RiotSharp/Caching/Cache.cs
RiotSharp/Caching/CacheData.cs
RiotSharp/Caching/FileCache.cs
RiotSharp/Caching/ICache.cs
RiotSharp/Caching/PassThroughCache.cs
RiotSharp/Endpoints/MatchEndpoint/MatchEndpoint.cs
RiotSharp/Endpoints/SummonerEndpoint/SummonerEndpoint.cs
RiotSharp/RiotApi.cs
RiotSharp/StaticRiotApi.cs

Move Cache classes to the new namespace.

Add a top-level Cache namespace #501

---

RiotSharp/Endpoints/MatchEndpoint/Enums/Season.cs

GetRecentMatches couldn't work without it soo....

Added season 2018

---

RiotSharp/Endpoints/MatchEndpoint/Enums/Converters/SeasonConverter.cs

Forgot there was a converter, tweaked it :p

2018 season converter

---

RiotSharp.AspNetCore/ApiKeyOptions.cs
RiotSharp.AspNetCore/IServiceCollectionExtension.cs
RiotSharp.AspNetCore/RiotSharpOptions.cs
RiotSharp/Endpoints/Interfaces/Static/IStaticChampionEndpoint.cs
RiotSharp/Endpoints/Interfaces/Static/IStaticItemEndpoint.cs
RiotSharp/Endpoints/Interfaces/Static/IStaticLanguageStringsEndpoint.cs
RiotSharp/Endpoints/Interfaces/Static/IStaticMapEndpoint.cs
RiotSharp/Endpoints/Interfaces/Static/IStaticMasteryEndpoint.cs
RiotSharp/Endpoints/Interfaces/Static/IStaticProfileIconEndpoint.cs
RiotSharp/Endpoints/Interfaces/Static/IStaticRuneEndpoint.cs
RiotSharp/Endpoints/Interfaces/Static/IStaticSummonerSpellEndpoint.cs
RiotSharp/Endpoints/StaticDataEndpoint/Champion/StaticChampionEndpoint.cs
RiotSharp/Endpoints/StaticDataEndpoint/Item/StaticItemEndpoint.cs
RiotSharp/Endpoints/StaticDataEndpoint/LanguageStrings/StaticLanguageEndpoint.cs
RiotSharp/Endpoints/StaticDataEndpoint/Map/StaticMapEndpoint.cs
RiotSharp/Endpoints/StaticDataEndpoint/Mastery/StaticMasteryEndpoint.cs
RiotSharp/Endpoints/StaticDataEndpoint/ProfileIcons/StaticProfileIconEndpoint.cs
RiotSharp/Endpoints/StaticDataEndpoint/Realm/StaticRealmEndpoint.cs
RiotSharp/Endpoints/StaticDataEndpoint/Rune/StaticRuneEndpoint.cs
RiotSharp/Endpoints/StaticDataEndpoint/SummonerSpell/StaticSummonerSpellEndpoint.cs
RiotSharp/Endpoints/StaticDataEndpoint/Version/StaticVersionsEndpoint.cs
RiotSharp/Http/Interfaces/IRateLimitedRequester.cs
RiotSharp/Http/Interfaces/IRequester.cs
RiotSharp/Http/RateLimitedRequester.cs
RiotSharp/Http/Requester.cs
RiotSharp/Http/RequesterBase.cs
RiotSharp/RiotApi.cs

- Add version parameter to static data endpoints
- Complete interface implementation of `IRiotApi`
- Fix unit test build errors
- Add more detailed cache keys: Each cache key varies now based on each request parameter

Add version parameter to static data endpoints

---

RiotSharp.Test/RiotApiTest.cs
RiotSharp.Test/RiotApiTestBase.cs
RiotSharp.Test/TournamentRiotApiTest.cs
RiotSharp/Endpoints/MatchEndpoint/MatchReference.cs

fixed #552
- Fix ignored tests
- Make tournament tests to be ignored by default
- Queue is Int now at the match endpoints

fix falling tests

---

RiotSharp/Endpoints/Interfaces/IMatchEndpoint.cs
RiotSharp/Endpoints/MatchEndpoint/MatchEndpoint.cs

All references to the deprecated endpoint have been removed. Issue #537

Deprecated RecentMatches

---

RiotSharp.Test/RiotApiTest.cs
RiotSharp.Test/StaticRiotApiTest.cs
RiotSharp/Endpoints/Interfaces/Static/IStaticChampionEndpoint.cs
RiotSharp/Endpoints/Interfaces/Static/IStaticReforgedRuneEndpoint.cs
RiotSharp/Endpoints/StaticDataEndpoint/Champion/StaticChampionEndpoint.cs
RiotSharp/Endpoints/StaticDataEndpoint/Item/ItemListStatic.cs
RiotSharp/Endpoints/StaticDataEndpoint/Item/ItemStatic.cs
RiotSharp/Endpoints/StaticDataEndpoint/Item/ItemsConverter.cs
RiotSharp/Endpoints/StaticDataEndpoint/ReforgedRune/Cache/ReforgedRuneListStaticWrapper.cs
RiotSharp/Endpoints/StaticDataEndpoint/ReforgedRune/ReforgedRuneStatic.cs
RiotSharp/Endpoints/StaticDataEndpoint/ReforgedRune/StaticReforgedRuneEndpoint.cs
RiotSharp/Http/RequesterBase.cs

Fixes for issues I found during migrating my application to the latest version.
Riot forgot to document these changes. 😠

DDragon migration fixes

---

RiotSharp/Misc/Converters/PlatformConverter.cs

Convert platform string to uppercase before parsing

---

RiotSharp/Endpoints/MatchEndpoint/Event.cs

Fixed event type JSON property name

---

RiotSharp.AspNetCore/DistributedCache.cs
RiotSharp.AspNetCore/HybridCache.cs
RiotSharp.AspNetCore/IDistributedCacheExtensions.cs
RiotSharp.AspNetCore/IServiceCollectionExtension.cs
RiotSharp.AspNetCore/MemoryCache.cs

Fixed the codestyle issues according to https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-managed-code-warnings?view=vs-2017, https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines and https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md
I will create a separate PR with the changes for RiotSharp because that a lot more code then the AspNetCore project.

Fix codestyle issues in RiotSharp.AspNetCore

---

README.md

It changes the readme to make the use of 'API' more consistent (all caps everywhere).
Only the README.md file is changed.
These changes should not have an impact on the software itself.

Changed the README.md for more consistency

---

RiotSharp.Test/CommonTestBase.cs
RiotSharp.Test/EndpointTests/SpectatorEndpointTests.cs
RiotSharp.Test/EndpointTests/ThirdPartyEndpointTests.cs
RiotSharp.Test/RiotApiTest.cs
RiotSharp.Test/RiotApiTestBase.cs
RiotSharp/Endpoints/ChampionMasteryEndpoint/ChampionMastery.cs
RiotSharp/Endpoints/ChampionMasteryEndpoint/ChampionMasteryEndpoint.cs
RiotSharp/Endpoints/Interfaces/IChampionMasteryEndpoint.cs
RiotSharp/Endpoints/Interfaces/ILeagueEndpoint.cs
RiotSharp/Endpoints/Interfaces/IMatchEndpoint.cs
RiotSharp/Endpoints/Interfaces/ISpectatorEndpoint.cs
RiotSharp/Endpoints/Interfaces/ISummonerEndpoint.cs
RiotSharp/Endpoints/Interfaces/IThirdPartyEndpoint.cs
RiotSharp/Endpoints/LeagueEndpoint/LeagueEndpoint.cs
RiotSharp/Endpoints/MatchEndpoint/MatchEndpoint.cs
RiotSharp/Endpoints/MatchEndpoint/Player.cs
RiotSharp/Endpoints/SpectatorEndpoint/SpectatorEndpoint.cs
RiotSharp/Endpoints/SummonerEndpoint/SummonerBase.cs
RiotSharp/Endpoints/SummonerEndpoint/SummonerEndpoint.cs
RiotSharp/Endpoints/ThirdPartyEndpoint/ThirdPartyEndpoint.cs
RiotSharp/TournamentRiotApi.cs

API version migration for several endpoints

V4 migration

---

RiotSharp.Test/CommonTestBase.cs
RiotSharp.Test/EndpointTests/ThirdPartyEndpointTests.cs
RiotSharp.Test/RiotApiTest.cs
RiotSharp.Test/RiotApiTestBase.cs
RiotSharp.Test/TournamentRiotApiTestBase.cs
RiotSharp/Http/RequesterBase.cs
RiotSharp/Misc/Converters/PlatformConverter.cs
RiotSharp/Misc/Converters/RegionConverter.cs
RiotSharp/Misc/Region.cs

Rename region enum names to start with uppercase letter

Rename region enums 

---

RiotSharp/RiotSharp.csproj

[RiotSharp.4.0.0.zip](https://github.com/BenFradet/RiotSharp/files/3065101/RiotSharp.4.0.0.zip)

Release 4.0.0
