RiotSharp/MatchEndpoint/Converters/Season.cs
RiotSharp/MatchEndpoint/Converters/SeasonConverter.cs

Proposed changes to support the new PRESEASON2015 response for the "season" response in MatchSummary. Not yet documented in the API, but I asked for information here: https://developer.riotgames.com/discussion/riot-games-api/show/uhWkZQWi
Changes have not been compiled or tested locally.

Support for "PRESEASON2015" response in matchhistory

---

RiotSharp/Requester.cs

Corrected two problems in the Requester. Riot has disallowed the use of the HTTP endpoints in favour of HTTPS instead. This is causing WebExceptions to be thrown which don't have WebResponses, resulting in NullReferenceExceptions. I made an addition which checks for this eventuality and throws a more descriptive error than NullReference.
Finally I changed the HTTP endpoints to HTTPS.

Bugfix jhallam

---

RiotSharp/Misc/MapType.cs

The non-seasonal (plain) version of Summoner's Rift is inexplicably missing from RiotSharp.MapType enum.

Added missing value to MapType enum

---

RiotSharpExample/RiotSharpExample.csproj
RiotSharpExample/packages.config

RiotSharpExample was using an old verison of the Newtonsoft.Json package
which was causing both to get downloaded. Consolidated to the
Newtonsoft.Json version of the main RiotSharp project.

Update RiotSharpExample NuGet packages

---

RiotSharp/IRiotApi.cs
RiotSharp/IStaticRiotApi.cs
RiotSharp/IStatusRiotApi.cs
RiotSharp/RiotApi.cs
RiotSharp/RiotSharp.csproj
RiotSharp/StaticRiotApi.cs
RiotSharp/StatusRiotApi.cs

Basically I just created Interfaces for each of the major API classes. I did this for two reasons:
Firstly, it allows for better use of Dependency Injection (specifically in Unit Testing). I can now Mock these objects to test code that would otherwise depend upon the results of API calls.
Secondly, it helps with Inversion of Control a bit.
Any questions or concerns, just lemme know.
Love the project and I'm using it in a personal project!
EDIT: Created an Issue about this earlier, then realized I could do it myself quickly with little effort. If you can associate this with the issue or just remove the issue, go ahead.

Put 3 API Classes behind Interfaces

---

RiotSharp/MatchEndpoint/Converters/Season.cs
RiotSharp/MatchEndpoint/MatchList.cs
RiotSharp/MatchEndpoint/MatchReference.cs
RiotSharp/Misc/Util.cs
RiotSharp/RiotApi.cs
RiotSharp/RiotSharp.csproj
RiotSharpExample/App.config
RiotSharpTest/App.config
RiotSharpTest/RiotApiTest.cs
RiotSharpTest/RiotSharpTest.csproj

The Match List endpoint can now be accessed through the wrapper however I cannot solve an issue causing 4 of my tests to fail. 
Both the Sync and Async GetMatchList_ChampionIds tests and GetMatchList_DateTimes tests seem to fail. This seems to be due to a failure during the deserialization of the Json within the class MatchReference. The properties champion and timestamp don't seem to deserialize properly and appear to pass as a default value of either: 
0 for the ChampionID,
01/01/0001 00:00:00 for the timestamp.

Adds the new match list endpoint to the wrapper

---

RiotSharp/Requester.cs
RiotSharpTest/RiotApiExceptionTest.cs
RiotSharpTest/StaticRiotApiExceptionTest.cs

As said in #203 I have removed try/catch and replaced it with error handling based on response status code. After that it has started to pass tests for expected exception.

Remove exception handlers from Requester

---

RiotSharp/RiotSharp.csproj
RiotSharp/TournamentEndpoint/Converters/TournamentEventType.cs
RiotSharp/TournamentEndpoint/LobbyEvent.cs
RiotSharp/TournamentEndpoint/TournamentLobbyEvent.cs

Change its type from string to enum as said in #185. I would like to test it, but I don't have tournament api key, so I would be glad if you can test it on your end.

Change lobby events' event type

---

RiotSharp/ChampionMasteryEndpoint/ChampionMastery.cs

I removed `HighestGrade` from the `ChampionMastery` class.
There were no tests written for this, so no changes there. Do let me know if there's anything that I might've missed out. 
Thanks for this opportunity!
ps: I checked your branch naming conventions and deduced that `RS-228` is what this branch should be named because it was issue #228. Will be happy to close this out and open another one if there are other branch naming conventions.
---
Fixes #228

Remove HighestGrade from ChampionMastery

---

RiotSharp/IStaticRiotApi.cs
RiotSharp/StaticDataEndpoint/DataRequested.cs
RiotSharp/StaticRiotApi.cs

`basic` makes more sense as compared to `none`. None gives a sense of
"nothing" but what this actually does is that it returns a basic set of
keys in the response, so `basic` makes more sense.
Fixes #231

Rename none to basic on all static data enums

---

RiotSharp/StaticDataEndpoint/Map/Cache/MapsStaticWrapper.cs

Bum me, I was assigning the property to itself, instead of using the parameter passed to the ctor.
Sorry about this, @BenFradet!
---
Fixes #236

bugfix: NullReferenceException on Maps caching

---

RiotSharp/Misc/Slug.cs

Hi,
When i ran the RiotSharpExample project i got an exception on function statusApi.GetShards()
It occurs when de-serializing the List<Shard>, since one of the Shards had a Slug that did not exist. 
In this case it was "kr" for "Republic of Korea".

Add Republic of Korea Slug

---

RiotSharp/GameEndpoint/Enums/Converters/GameSubTypeConverter.cs
RiotSharp/GameEndpoint/Enums/GameSubType.cs

The new 2017 season has a flexible queue mode, which is already referenced in the official API. In addition, GameSubType enum lack Siege and Hexakill 6x6 modes.

Added missing game subTypes according to actual API reference.

---

RiotSharp/MatchEndpoint/Enums/Converters/QueueTypeConverter.cs
RiotSharp/MatchEndpoint/Enums/QueueType.cs
RiotSharp/Misc/Queue.cs
RiotSharp/Misc/QueueConverter.cs

Added missing queue type TEAM_BUILDER_RANKED_SOLO to queue enums in Queue.cs and QueueType.cs along with their respective type converters. Resolves issue #289.

Added Queue Type to Enums

---

RiotSharp/RateLimitedRequester.cs
RiotSharp/RateLimiter.cs
RiotSharp/RiotSharp.csproj
RiotSharpTest/RateLimiterTest.cs
RiotSharpTest/RiotSharpTest.csproj

#296
There are some tests for the RateLimiter which confirm that it is working properly (at least for the 10 second limit). They are pretty janky since it's a time-based component.
RateLimiter also has a `SetRetryAfter(...)` functionality for when requests return a `RetryAfter` header (429) but it is currently not used (would require more changes to the way the RateLimitedRequester is laid out).

Use per-region rate limiter

---

RiotSharp/Misc/Queue.cs
RiotSharp/Misc/QueueConverter.cs

Addresses RS-302 (#302). However, these values are deprecated per: https://developer.riotgames.com/docs/game-constants

Add RANKED_PREMADE to Queue enums

---

RiotSharp/ITournamentRiotApi.cs
RiotSharp/TournamentRiotApi.cs
RiotSharpTest/TournamentRiotApiTest.cs

Added a parameter validation to the `TournamentApi`.
Added empty corresponding unit tests, because I don't have a tournament api key. 
I'm wondering if I should take over the [Requester interface pull request](https://github.com/BenFradet/RiotSharp/pull/253) to make the unit tests work without real API calls.

Added validation to TournamentApi (#362)

---

RiotSharpTest/TournamentRiotApiTest.cs

Added correct number of parameters to Tournament API tests. Passed an empty list of Longs for missing summonerIds parameter, passed an empty string for the missing metadata parameter.

Added correct number of parameters to Tournament API tests. Fixes Issue #369.

---

RiotSharp/RiotApi.cs

Renamed `TeamBySummonerURL `to `TeamBySummonerUrl` in RiotApi.

Coding convention fix

---

RiotSharp/Cache.cs
RiotSharp/Http/Interfaces/IRequester.cs
RiotSharp/Http/RateLimitedRequester.cs
RiotSharp/Http/Requester.cs
RiotSharp/Http/RequesterBase.cs
RiotSharp/ICache.cs
RiotSharp/RiotApi.cs
RiotSharp/StaticRiotApi.cs
RiotSharp/StatusRiotApi.cs
RiotSharp/TournamentRiotApi.cs
RiotSharpExample/Program.cs
RiotSharpTest/StatusRiotApiTest.cs
RiotSharpTest/TournamentRiotApiTest.cs

Prepared `Requester `classes and the `Cache `class for DI:
- Set access modifier to `public`
- Improved constructors
Added DI constructors to api endpoints
Fixed `TournamentApiTest `(wrong api key reference)

Added DI constructors to Api endpoints

---

RiotSharp.AspNetCore/ApiKeyOptions.cs
RiotSharp.AspNetCore/IServiceCollectionExtension.cs
RiotSharp.AspNetCore/RiotSharpOptions.cs
RiotSharp.Test/RateLimiterTest.cs
RiotSharp.Test/RiotApiExceptionTest.cs
RiotSharp.Test/RiotApiTest.cs
RiotSharp/Http/Interfaces/IRateLimitedRequester.cs
RiotSharp/Http/RateLimitedRequester.cs
RiotSharp/Http/RateLimiter.cs
RiotSharp/RiotApi.cs
RiotSharp/TournamentRiotApi.cs
RiotSharpExample/Program.cs

Tests pass locally (don't have tournament key). Not sure if CI is updated for the new system so...

Update RateLimiter to use dictionary of rate limits (fixes #437)

---

RiotSharp/Http/RateLimitedRequester.cs
RiotSharp/StaticRiotApi.cs

Closes issue [Move to the api.riotgames.com domain #347](https://github.com/BenFradet/RiotSharp/issues/347)

Replaced all instances of api.pvp.net with api.riotgames.com

---

RiotSharp/StaticRiotApi.cs

Due to new rate limits to the static endpoint, which are 10 requests per hours, the default sliding expiration time has to be raised to avoid 429 errors.

Raised default sliding expiration time to 1 hour

---

README.md
RiotSharp/StaticDataEndpoint/StatsStatic.cs

* Changed how you get a summoner
* Added a deprecated tag to the summoner.GetRankedStats() blurb
* Created a blurb on how to get champion masteries as a means of displaying the interaction between regular and static api. (Not sure if this is necessary, but thought I may as well add ¯\_(ツ)_/¯ ).
Note: for some reason it isn't seeing the change to StatsStatic.cs from before :/

Updated README.md to align with latest build

---

RiotSharp.Test/RiotApiTest.cs
RiotSharp/Interfaces/IRiotApi.cs
RiotSharp/RiotApi.cs
RiotSharp/RunesEndpoint/RunePage.cs
RiotSharp/RunesEndpoint/RunePages.cs
RiotSharp/RunesEndpoint/RuneSlot.cs
RiotSharp/SummonerEndpoint/SummonerBase.cs

- Migrated the RunePages, RunePage, and RuneSlot DTOs to their own RuneEndpoint folder and updated namespaces for affected files.
- Unit tests updated and brought in line with unit tests used for mastery pages.
- GetRunePages and GetRunePagesAsync now call from the V3 endpoint.
Only concern is that this commit doesn't deal with the SummonerBase class, which currently still gets data from the depreciated endpoint. It  still gets mastery pages from the depreciated endpoint, which may have been missed from the mastery page migration to V3. I can either update the class to use the new rune endpoint, or I can leave it as is and focus on revamping the class in a new issue / commit.

Added RUNES-V3 endpoint and migrated relevant DTOs [Fixes Issue #350]

---

RiotSharp.Test/RateLimiterTest.cs
RiotSharp.Test/appsettings.json
RiotSharp/Http/RequesterBase.cs
RiotSharp/RiotApi.cs
RiotSharp/StaticRiotApi.cs
RiotSharp/TournamentRiotApi.cs

Only replaced when the string.Format first parameters was NOT a var.

Replace string.Format by string interpolation

---

RiotSharp/Endpoints/ChampionEndpoint/ChampionEndpoint.cs
RiotSharp/Endpoints/ChampionMasteryEndpoint/ChampionMasteryEndpoint.cs
RiotSharp/Endpoints/LeagueEndpoint/LeagueEndpoint.cs
RiotSharp/Endpoints/MasteriesEndpoint/MasteriesEndpoint.cs
RiotSharp/Endpoints/MatchEndpoint/MatchEndpoint.cs
RiotSharp/Endpoints/RunesEndpoint/RunesEndpoint.cs
RiotSharp/Endpoints/SpectatorEndpoint/SpectatorEndpoint.cs
RiotSharp/Endpoints/SummonerEndpoint/SummonerEndpoint.cs
RiotSharp/Http/RateLimitedRequester.cs
RiotSharp/Http/RateLimiter.cs
RiotSharp/Http/Requester.cs
RiotSharp/Http/RequesterBase.cs
RiotSharp/StaticRiotApi.cs
RiotSharp/StatusRiotApi.cs
RiotSharp/TournamentRiotApi.cs

Added .ConfigureAwait(false) to async Methods. 
GetAsync() now only gets the ResponseHeaders.
- By adding .ConfigureAwait(false) to all the async Methods, the Json-Serialization is automatically run on the ThreadPool. (Also kinda helps against .Result-/.Wait-Deadlocks, by not waiting for the blocked context)
- GetAsync only needs the Headers, because it's being followed up by GetResponseContentAsync. This way there is no MemoryStream created when reading the response content.

Refactored Async Methods

---

RiotSharp/Endpoints/GameEndpoint/RawStat.cs
RiotSharp/Endpoints/MatchEndpoint/Match.cs
RiotSharp/Endpoints/MatchEndpoint/MatchSummary.cs
RiotSharp/Misc/Converters/TimeSpanConverterFromS.cs

Changes gameDuration JSON property from milliseconds to seconds to comply with League of Legends API at the time of this patch. Also cleans up name from "TimeSpanConverterFromS" to "TimeSpanConverterFromSeconds" to match the millisecond converter name.
This is from https://developer.riotgames.com/api-methods/#match-v3/GET_getMatch
You can see the gameDuration property returns a long. This value is returned in seconds. This has been tested and verified locally.

Change gameDuration from milliseconds to seconds

---

RiotSharp/Misc/Converters/LaneConverter.cs
RiotSharp/Misc/Lane.cs

Parser crashes when pulling anyone with an ARAM game in the match history.

Fix for ARAM matches

---

RiotSharp.Test/RiotApiExceptionTest.cs
RiotSharp.Test/RiotApiTest.cs
RiotSharp/Endpoints/ChampionEndpoint/ChampionEndpoint.cs
RiotSharp/Endpoints/Interfaces/IChampionEndpoint.cs

Issue #581 
Removed deprecated champions endpoint and the associated `GetChampionsAsync` methods and tests.
I am getting a failed test for `GetMatchListAsync_Seasons_Test` but I think that might be an unrelated issue as it seems to happen without the changes I've made.

Remove deprecated champion endpoint #581

---

RiotSharp/Misc/Converters/PlatformConverter.cs

When serializing a game which contains bots and `platformId = ""`, the `platformId` is serialized to `NOPLATFORM`, which fails the roudtrip deserialization.

Added roundtrip serialization for Platform.NoPlatform

---

RiotSharp/Http/RateLimitedRequester.cs
RiotSharp/Http/Requester.cs
RiotSharp/Http/RequesterBase.cs

Refactored RequesterBase so it uses "X-Riot-Token" HTTP-Header instead of "api_key" querystring.
Metadata belongs to the HTTP Requestheaders and it overall seems wrong to "put authorization into a url" also improves possible future caching logic, where the cache-key might be combined from the querystring

Use X-Riot-Token Header instead of api_key querystring

---

RiotSharp/Misc/Converters/PlatformConverter.cs
RiotSharp/Misc/Platform.cs

I noticed some deserialization errors due to the JP1 platform not being present.

Added JP1 platform

---

RiotSharp/Http/RequesterBase.cs

Fixed an issue where getting multiple error consecutively (like 404) would result in "A task was canceled" because the response would never be disposed after such error.

Dispose Response Object on Error

---

RiotSharp.Test/EndpointTests/SpectatorEndpointTests.cs
RiotSharp/Endpoints/MatchEndpoint/Enums/Converters/MatchEventTypeConverter.cs
RiotSharp/Endpoints/MatchEndpoint/Enums/MatchEventType.cs
RiotSharp/Endpoints/MatchEndpoint/MatchEvent.cs
RiotSharp/Endpoints/MatchEndpoint/MatchFrame.cs
RiotSharp/Endpoints/MatchEndpoint/MatchTimeline.cs

- Renamed `Frame`, `EventType` and `Event` to `MatchFrame`, `MatchEventType` and `MatchEvent` 
- Fixed loading of `ItemAfterId` and `ItemBeforeId`

Match endpoint fixes
